# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WaterPurification
                                 A QGIS plugin
 Water Purification
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-23
        copyright            : (C) 2025 by ICRA
        email                : ollorente@icra.cat
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'ICRA'
__date__ = '2025-04-23'
__copyright__ = '(C) 2025 by ICRA'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WaterPurification class from file WaterPurification.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .water_purification import WaterPurificationPlugin
    return WaterPurificationPlugin(iface)
